name: FinRL3
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - pytorch-gpu
  - pytorch-cuda
  - cudatoolkit
  - jupyterlab
  - jupyter
  - diskcache
  #- pip
  #- pip:
  #    - -r requirements.txt