version: "3.8"

services:
  trader:
    image: cs221:trade
    build: ./trade.Dockerfile
    #container_name: optuna_worker
    #ports:
    #  - 8888:8888
    volumes:
    #  - ./:/workspace
    #  - diskcache:/mnt/diskcache
      - artifacts:/mnt/artifacts
    networks:
      - cs221_finrl

volumes:
  artifacts:

networks:
  cs221_finrl:
    external: true