version: "3.8"

services:
  worker:
    image: cs221:train
    build:
      context: .
      dockerfile: train.Dockerfile
    restart: always
    #container_name: optuna_worker
    #ports:
    #  - 8888:8888
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
    #  - ./:/workspace
    #  - diskcache:/mnt/diskcache
      - artifacts:/workspace/examples/artifacts
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - NB_UID=1000
      - NB_GID=100
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS='-R'
      - CHOWN_EXTRA_OPTS='-R'
      - N_TRIALS=${N_TRIALS:-100}
      - N_PROCESSES=${N_PROCESSES:-2}
      - POSTGRES_HOST=postgres
    networks:
      - cs221_finrl

  postgres:
    image: postgres:14-alpine
    # Alfred for allowing more workers
    command: postgres -c 'max_connections=400'
    ports:
      - 5432:5432
    volumes:
      - optuna-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alfred"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=Cc17931793
      - POSTGRES_USER=alfred
      - POSTGRES_DB=optuna_db
    networks:
      - cs221_finrl

volumes:
    optuna-postgres:
    artifacts:
    #diskcache:

networks:
  cs221_finrl:
    external: true